Chapter 3
=========

``AtomicBuzz(TM)?''

``No thanks. The only thing that gets me high is justice.''

Cosgrove worries picking this guy up was a mistake. Sidekicks are handy as meat 
shields. Talking is a big headache. Sten fumbles with the radio. 99.9 is pumping 
out the bourgeois-metal stylings of Grocery Store Gulag

====

So you wanna take part in democracy
You're just filling in circles on a bunch of dead trees
I vote with my dollar, I buy consumer goods
Just like Satan and his minions would

====

Sten jumps in the back seat and picks up his mop. He starts riffing on those 
threads of yarn so hard a few of his fingers break. Up ahead, Unified School 
District School Bus No. 8 rams a SWAT vehicle off an overpass.

'''

Edward is no hero, but he'll be damned if he lets a few police officers with 
nothing better to do ruin this field trip. Dinosaurs are about the only thing 
that Edward cares about.  The Anklyosaurus is the perfect being. To his 5th 
grade mind it's impossible to believe that a living tank could ever go extinct.  
This trip to the natural history museum is the first step to proving the 
continued-- possibly underground, possibly secret --life of the Anklyosaurus.  
Mr. Gibbons had threatened to end Edward's dream after someone hit the back of 
his head witha grape sized spitball. Fortunately, Edward had shared his vision 
with the others before the trip. It didn't take him long to gather a team. Sally 
played sick. Gibbons is a known emetophobe. After the bus was pulled over they 
cornered him with their paper shivs. Gibbons tries to fight, but Billy plants 
a deep cut between his right thumb and index finger. Marilyn is going through 
their natural history text book with him in an attempt to convert him quickly as 
possible. Not even Gibbons could scoff at an armored, six ton killing machine.  
The kids could handle things for a while, but getting out of the country without 
an adult would be a hassle. If they can't convert Gibbons they'll have to ransom 
him. Edward knows they'll need to charter a plane or ship.

``Ed, why the heck are they doing this?'' says Sally.

``Some do-gooder with a hands-free headset and no life must've called it in,'' 
says Edward.

``Nah, we took his phone right away,'' says Joe. ``Henry called called the 
principal and said we'd be stuck in traffic until Monday.''

Henry's voice had already cracked. The pituitary freak is coming in handy.

``And now,'' says Edward, swinging the bus to the left. ``To the task at hand.''

'''

The bus dives back to the right. Cosgrove slams the brakes and swerves. It just 
misses. Putting the Mental Transceiver back on was obviously a bad idea. She 
feels like she has paper cuts all over. The idiot behind her is beaming a Metal 
concert into her head. All she can think about is dinosaurs.


