Chapter 3
=========

``AtomicBuzz(TM)?''

``No thanks. The only thing that gets me high is justice.''

Cosgrove worries picking this guy up was a mistake. Sidekicks are handy as meat 
shields. Talking is a big headache. Sten fumbles with the radio. 99.9 is pumping 
out the bourgeois-metal stylings of Grocery Store Gulag

====

So you wanna take part in democracy +
You're just filling in circles on a bunch of dead trees +
I vote with my dollar, I buy consumer goods +
Just like Satan and his minions would +

====

Sten jumps in the back seat and picks up his mop. He starts riffing on those 
threads of yarn so hard a few of his fingers become dislocated. Up ahead, 
Unified School District School Bus No. 8 rams a SWAT vehicle off an overpass.

Edward is no hero, but he'll be damned if he lets a few police officers with 
nothing better to do ruin this field trip. Dinosaurs are about the only thing 
that Edward cares about.  The Anklyosaurus is the perfect being. To his 5th 
grade mind it's impossible to believe that a living tank could ever go extinct.  
This trip to the natural history museum is the first step to proving the 
continued-- possibly underground, possibly secret --life of the Anklyosaurus.  
Mr. Gibbons had threatened to end Edward's dream after someone hit the back of 
his head witha grape sized spitball. Fortunately, Edward had shared his vision 
with the others before the trip. It didn't take him long to gather a team. Sally 
played sick. Gibbons is a known emetophobe. After the bus was pulled over they 
cornered him with their paper shivs. Gibbons tries to fight, but Billy plants 
a deep cut between his right thumb and index finger. Marilyn is going through 
their natural history text book with him in an attempt to convert him quickly as 
possible. Not even Gibbons could scoff at an armored, six ton killing machine.  
The kids could handle things for a while, but getting out of the country without 
an adult would be a hassle. If they can't convert Gibbons they'll have to ransom 
him. Edward knows they'll need to charter a plane or ship.

``Ed, why the heck are they doing this?'' says Sally.

``Some do-gooder with a hands-free headset and no life must've called it in,'' 
says Edward.

``Nah, we took his phone right away,'' says Joe. ``Henry called called the 
principal and said we'd be stuck in traffic until Monday.''

Henry's voice had already cracked. The pituitary freak is coming in handy.

``And now,'' says Edward, swinging the bus to the left. ``To the task at hand.''

The bus dives back to the right. Cosgrove slams the brakes and swerves. It just 
misses. Putting the Mental Transceiver back on was obviously a bad idea. Why had 
she gotten on the highway in the first place? She just asked a question. That 
mens more questions.

Why had she driven into this mess? Maybe it was the Metal. Why can't she stop 
thinking about dinosaurs?

Anklyosaurus munches. The leaves rustle above him. Branches snap under his feet. 
He feels the Green speak to him. The Green sustains him. It passes through him 
imparting its wisdom. He cannot fathom what the Green must know. The Green is 
everywhere and Anklyosaurus goes wherever the Green provides. Sometimes the Sky 
or Ground will call to Anklyosaurus. He will obey them, but only grudgingly. 
They are Green's siblings but do not share it's patience. The Sky yells. The 
Ground shakes. The Green grows. He is grateful for every leaf.

There is a scent on the wind. Sky has sent another servant. Sky and its servants 
are always shouting. This one has the teeth. Anklyosaurus will have to break his 
bones. It is ugly but necessary. The teeth will scream before his bones are 
broken and after his bones are broken. The smell is stronger now. He is close. 
Rex will scream at Anklyosaurus, but he is ready. He feels the weight of his 
tail. He is balanced.

Rex has no patience for the Green. Like Sky, he pushes everything away. Leaves 
and branches crunch and snap. Anklyosaurus treads on what the Green has cast 
away to Ground, but he does not take from Green its limbs. Rex is selfish.

The last of the Green between them parts. Rex bears his teeth and screams like 
Sky. Anklyosaurus is no twig. He has learned from the Green. His roots do not 
move. They grip stone and dirt alike. Rex plunges forward, eager for Red Life. 
Anklyosaurus ducks his head low and pushes his body forward. Rex has a big 
mouth, but not big enough to fit Anklyosaurus. Rex's teeth scrape across the 
bumps and come together with nothing in between. Anklyosaurus spins. He kicks 
with both legs just before his tail reaches teeth. A vibration runs down his 
tail. He hears the wet thud of Green against Sky. Rex falls. Anklyosaurus is 
strong but this Rex has strong bones. When Rex gets up he will be more cautious. 
Anklyosaurus faces teeth once again. As he tries to stand the wet leaves he 
shook down slide under his feet. Anklyosaurus knows this is a gift from the 
Green. He spins again, hoping this will not be the day the Green takes him back. 
He hears the same wet thud but this time there is a snap. Anklyosaurus looks 
back and sees Rex with his mouth open and his bottom teeth swinging back and 
forth. He screams through his broken teeth. He no longer screams for Sky. He 
cries for something Anklyosaurus does not know. Anklyosaurus lifts his tail. He 
is sad for Sky's child. There is one last thud. The crying stops.

Anklyosaurus leans down near Rex. HE gathers a mouthful of the leaves that saved 
his life. Anklyosaurus munches.

Anklyo--Cosgrove takes a pencil to the side of the head. Sten has the protection 
of his mop, a surprisingly effective pencil deflector. The kids are using Joe's 
electric sharpener for quick reloading. Marilyn gathers up the shortest pencils 
and pokes them through a few three rings binders and some math flash cards. Joe 
manages to convince the others this qualifies as an emergency and therefore the 
back door should be open. Henry advises caution, things could get dangerous. He 
caves when reminded of his obligation to Anklyosaurus. Once it's open, Marilyn 
heaves her makeshift spike strip and assorted caltrops out the back.

A Lisa Frank dolphin binder lands nails the right front tire of the lead pursuit 
vehicle. The broken rubber drags it into the armored personnel carrier to its 
right. Sparks fly as the armor grinds kisses the jersey. Cosgrove is pacing the 
bus ahead of the carnage. The spinning cruiser catches the two vehicles behind 
it. The rest fall like dominoes. The entire column disappears in the distance.

Cosgrove realizes the safest place is ahead of the bus. She jams the Sebring 
back into 4th gear and plants it right in front. Take the wheel Shurdike, she 
yells. Aye ma'am. She hits the cruise control and slides into the passenger 
seat. Instead of taking her place. Sten jams his mop into the steering wheel and 
twirls an imaginary lasso with his left hand.

Cosgrove kneels in the back seat and tries to wave the kids down. Edward shakes 
his head. He points two fingers at Cosgrove and Sten before dragging them across 
his throat. When he lifts and turns his head to make the gesture Cosgrove sees 
it: a small black disk behind his ear. Now it makes sense. No it doesn't. She 
lifts her hair and points to her own disk. Edward laughs and shouts at everyone 
in the back. Marilyn and Joe put down their seat spring harpoon gun.

Pull us along side em', says Cosgrove. A twist of the mop and they're next to 
the bus door. Marilyn pulls the door handle. The flashing stop sign swings out 
and nearly smacks Cosgrove out of the car. She hops on over to the bus. Now free 
of his babysitter, Sten starts spanking himself and swings behind the bus into 
the car pool lane. Meat Eating Marshmallow Man blares across all four lanes.

====

The clown is here kids, don't be shy +
He's lean, he's mean, he'll make you cry +
But here's the trick, just take a bit +
you'll find out that he tastes alright +

====

``You got the ADD too lady?''

``I'm asking the questions. Where'd you get that disk.''

``A psychogeologist showed up one day and said we all had ADD. Said these disks 
were supposed to help us focus. Where'd you get yours?''

``Mail order.''

``Self-diagnosis isn't healthy.''

``Uh-huh. Now what was this psychologist's name?''

``Psycho__geologist__, he kept repeating it.''

``Name?''

``Denny. Like the restaurant is his.''

If Cosgrove hadn't thought that name earlier she would've thrown the little tyke 
right out of the bus. What's this guy doing with a bunch of 5th graders?

``Osborn? Dr. Denny Osborn''

Something lands on the roof.
