Chapter 1
=========

A certain bus drives along its regular route. Waves of stop and go traffic crash 
against it. Every turn, brake, and acceleration is the action of a complex 
system spanning streets, stop signs, avenues, stop lights, highways, 
interstates, railroads, crosswalks, sidewalks, docks, shipping lanes, 
drive-through lines, space ports, space stations and who knows what else. Each 
part connected to its neighbors, pushing and pulling, creating one tremendous 
vibration. [TODO: Add something about overtones] Each action contributes to one 
gestalt, globe-spanning entity that at this very moment is becoming concious. 
Every bit of information stored in this fevered cortex is at the cusp of total 
self-organization. The bus arrives at one of its scheduled stops. After a pause 
and a quick look around, the bus driver once again prepares to leave port. 
Though he would never admit it, the driver can feel himself as part of the 
stream, just like any driver that finds his or her self miles down the road 
without remembering how exactly he or she got there. The blood cell reenters the 
vein.

Sten Shurdike arrives a little late. He chases after the bus. The other 
passengers try not to notice him as he flails his arms and bangs on the rear 
door. It's Sten's first day of work, otherwise he'd let it go. Despite proper 
training and common sense, the bus driver hits the brakes.

The man driving the car behind the bus takes his eyes off the Axe Body Spray 
billboard just in time to stop. The stress on the system is immediate and 
irreversible. A wave of breaking spreads back from the bus to the freeway on 
ramp. On the freeway several dozen drivers emit a unique and highly irregular 
stream of profanities in perfect unison, though no one notices. The disturbance 
grows, both in strength and hideous complexity. Just as the nascent 
super-conciousness feels the first fiber of self brush against its mind, 
a terrible wave sweeps it back in the chaotic sea that birthed it. The few 
entities to observe this violence can only describe it as ``divine.''

The bus driver is trying to remember what he was just thinking as Sten steps 
onto the bus. The other passengers are still trying to ignore the situation. 
Sten seats himself on the port side, facing out the starboard windows.  He's 
always managed to keep starboard and port straight. Port is the right wine.

This is the first day of Sten's janitorial life. It's not the life he imagined, 
but it's not one he minds. As soon as he'd responded to the job listing two 
weeks ago Sten had outlined the ways he had lived a janitor-positive life. Most 
of the items applied to the service industry in general. As he catches his 
breath, Sten goes over the list again.

He was always appreciative of janitors. Mostly to himself, but he can recall 
a few specific times when he said something like ``glad he's here to clean that 
up,'' or ``that's a whopper of a mess. Good luck!'' He didn't like to bother 
people while they were working but he would wave or nod if they didn't seem 
engrossed in what they were doing. He always tipped well for good service, that. 
He'd never tipped a janitor, of course. If tipping janitors were the social 
norm, Sten certainly would. A janitor would go about his business, every now and 
then someone would walk up to the janitor and give them a few bucks. There would 
be a silent acknowledgement that the tipper had just used the facilities. The 
tip amount would be a judgement on the appearance, odour, and texture of the 
lavatory. Sten sits back, confident in his own attitude.

As he's about to descend into another alternative janitorial compensation 
fantasy, something catches his eye.

        CEDAR COSGROVE, PRIVATE INVESTIGATIONS
        47 S. 7th Ave
        555-555-2952
        I'm the one who asks the questions!
        No Faxes!!!

Seems combative. A few workers are slowly peeling the ad off a bus stop. The
graffiti is distracting, but tasteful. A fire truck roars past. Crazy traffic,
says the fireman. Absolutely possessed, says the other. Sten spots the smoke
billowing ahead. Right next to work, he'll have to smell it all day. They might
have him cleaning up smoke damage to the building. He can barely mop, they can't
ask him to clean up smoke damage. And really, smoke damage is more about
restoration than cleaning. Sten is probably going to have to explain all of this
to his boss. He may not know much about cleaning in a professional setting, but
Sten sure knows how little other people know about it. Well never mind, folks.
That's work that's burning. The [NOTE: likely to change]Harrison Safety
Controls, Inc.  building is completely engulfed in flames.

Three firetrucks are pumping water into the ground floor windows. A charred
corpse hangs out of a second story window. A group of firemen are putting on
protective equipment, including masks and oxygen tanks. The stench is terrible.
Imagine burning the chair that your manager has been farting into for twelve and
half years he's been with the company. Then throw in pencils, pens, printers,
toner, and the community fridge. Sten remembers burning his G.I. Joe's and his
sisters' Barbies.

``These kids huh,'' says Joe.

``Tell me about it,'' says Barbie.

``We were big stuff once. I'm getting worried.''

``Why Joe Baby?''

``We're never going to make it to this college thing.''

``And so what?''

``We'll get boxed up.''

Barbie chewed her gum a little faster. Joe shifted the strap on his M72 LAW
Rocket Launcher.

``And not together,'' says Joe.

``Joe!''

``We all came from from The Box, darling.''

``Sure did baby, but I ain't going back.''

``Maybe this was always the way it was going to be.''

``All I know is, our love was meant to be.''

Joe and Barbie shared one last passionate kiss. Barbie applied can after can of
hairspray. Joe unsealed his napalm canisters.

``They're gonna smell our love in heaven,'' said Joe as he dropped the lighter.

Barbie's hair curled and shrank. Joe's pecs dripped onto his abs. They embraced
until it wasn't necessary. They died as one piece of pink plastic.

``Can I help you sir?''

He's a stern looking detective. Sten doesn't quite know what to say. `I'm here
to clean all this up' seems a little sick.

``I'm Sten. Shurdike.''

Instant surprise on the detective's face. Quickly replaced by suspicion and
glee.

``Nice of you to arrive Mr. Shurdike- Mr. Shurdike has arrived.''

Two officers and another detective leave a paramedic and scramble over.

``We've been waiting to speak with you.''

The officer points to a few items on the company lawn. It takes Sten a few
moments to recognize them, a mop and bucket.

``Care to explain?''

Against smoke and emotion, Sten struggles over to the display. Near mop and
bucket is a smaller mop and bucket. Probably made out of tin, with a red glossy
paint the small bucket turns out to be holding a mop shaped pen. Next to the mop
is a Sten Shurdike name plaque. There's also a box of Swedish Fish.
Taped to the edge of the small bucket is an envelope. One of the officers
protests as Stan pops the envelope open, but doesn't have the heart to keep it
up. A dozen or so signatures surround some large block lettering.

           Welcome Sten,
        and Enjoy the Show!

A firefighter marches up to the detectives and shouts something. Recognizing the
lack of response from the officers, he peels off the helmet and mask.

``The idiots blew themselves up.''

``With what?'' Says the, now obviously junior, detective.

``Twenty pounds of black powder. Fireworks. Mostly mortars as far
as we can tell.''

Everyone waits for him to elaborate.

``Looks like they were planning some type of display. They were all gathered in 
the break room when the show started. Anyone not killed in the initial blast was 
disoriented and on fire.''

He pointed to the charred corpse in the second story window.

``No survivors?'' says the, now obviously senior, detective.

``According to the HR files we found, the only employee not accounted for is
Sten Shurdike.''

Sten tells them everything they want to hear, which is also the truth. No one
had ever died for Sten Shurdike before. They died for him but he's not grateful.
And why should he be? He wanted a simple life. He had had a simple life. Fifteen
pyromaniac safety engineers had stolen that dream from him. Sten asks if he's
free to go. The detectives say sure thing. What about the bucket? Knock
yourself out kiddo.

Sten retreats to the bus, mop in hand. He left the bucket, too cumbersome. He
steps on board. Again, he sits on the port side and gazes out the starboard
windows. As the bus pulls out, it's almost hit by a rubbernecking motorist. The
bus driver releases a unique and highly irregular stream of profanities. Sten 
looked down at the card his dead coworkers had made for him. Dopes.

The bus driver turns her heard to the back of the bus. Rather than the usual 
side-to-side route, she tilts it back until Sten is looking at her face upside 
down.

``This is a one way trip to hell, buddy.''

Sten's knuckles get a bit whiter. The head of the mop sways back and forth like 
a bead curtain between them.

``Is it?''

``You've been a bad janitor.''

``I haven't been a janitor.''

The other passengers are staring. Every one of them is wagging his or her finger 
at him. All of them are using the left hand. Sten gives himself a little pat on 
the back for such as astute observation. The glow fades quick. With 17 people on 
the bus, the statistical likelihood of all of them being left-handed is 
minuscule. There are a few possibilities: posession-- mass possession to be 
exact --, thought control, special effects, a delusion on Sten's part, or just 
good ol' conspiracy.

``We're here to talk to you buddy-boy.''

The passengers stand up one by one. Every left-hand index finger still in full 
wag. Sten stabs the tap strip so hard he thinks his hand might break.

        STOP REQUESTED

Lights up big and red. The soothing voice of public transportation repeats 
Sten's request. The driver's head snaps forward so hard it bounces off the 
steering whell. The passengers fall into their seats and appear to be fast 
asleep, except for their left-hand index fingers. After an abrupt stop, Sten 
exits through the read door.

Two men are waiting for Sten.

``Mister-''

``Shurdike-''

``we would-''

``like to-''

``speak with-''

And then in unison, ``you.''

Now, there is inside every man and woman a point from which safe return is not 
possible. Once reached, the perspective from this point will shatter that 
person's world view. Only through radical reorganization or aggressive 
self-delusion can a psyche survive. Sten has reached this point. The center will 
not hold. He's suddenly reminded of a song by Rental Car Regicide.

====

I felt bad 'bout something I did today +
WAHHHH +
So, I tore out my conscience and fed it to the flames +
YEAHHHHHHH +
Then I felt bad about tearing it out +
WHOAAAAAAAAAAA +
So I put it back in and it burned my insides +
OUTTTTTTTTTTTTTTTT

====

``Eat mop shitlords!''

Sten winds up and swings. The base of the mop head catches his target on the 
left temple.  The tassles whip around and tangle themselves on the shaft. The 
other one tries to help his hapless partner. Due to some strange sympathetic 
reflex, he's is having similar difficulties breathing and seeing.  Sten kicks 
the first one in the gut, spinning him like a top out of the mop's clutches.  
Sten does a quick 180 with the mop and plants the end of the handle right on the 
other's solar plexus. The handle passes through like he's made of cardboard.

``When I was a janitor I took crap from everyone. Those days are over. I'm 
a freelancer now. I'll clean up the messes as I see fit.''
