Chapter 2
=========

Cedar Cosgrove takes a long drag off her e-cigarette. AtomicBuzz(TM) Caffeinated 
Lithiated Low-Deliriant Weapons Grade D-Nicotine E-Juice now comes in an 
exciting array of colors and flavors. Cosgrove has been pumping gold brussel 
sprout into the room for the past seven hours. Once golden and bright, the mist 
has soured into a musky sepia haze. Her left pupil dilates as she exhales. The 
venetian blinds illuminate the cloud in layers. Swirling patterns appear at the 
edges. Marble cake is on Cosgrove's mind.

Her right eye dilates as the office door swings open. Any appointments? No. Is 
the secretary here?  Don't have one. His weapon is half way out of the holster 
when the intruder's foot appears from behind the door. The barrel is level when 
they lock eyes. A shot. The intruder lifts his hands to his face.  Hot lead 
bounces of his sixth rib, tears through his right lung, and embeds itself in his 
second and third thoraic vertebrae. He hits the floor with his mouth open. For 
one sweet moment Cosgrove thinks she can see it. Perhaps, that's just the tip of 
a forked tongue--

This D-Lux Trans-Cortical Omni-Band Mental Receiver is hands down the most 
useful thing Cosgrove has ever ordered out of the back of Popular Science. Even 
the interference is fun. Only trouble is the story behind it. The thing isn't 
meant for single solitary use. It's for networking. There's some real high 
dollar R&D behind this sucker. Cosgrove's lucky to have her hands on it.

But the fun's over. It's time to start asking questions. Questions are 
a nightmare. Questions lead to answers. Answers lead to more questions. One 
woman only has so much time. Despite that slippery slope. Something tells 
Cosgrove this was a question worth asking.

She pasted the dime sized disk behind her ear after breakfast. In a few hours 
the tingling had stopped. She first noticed the effects after pending an hour 
reading about dog nutrition and exercise. The topic was interesting, but she 
couldn't shake the feeling that the impulse had come from outside herself.  
Later she even felt a little bad about using her e-cig so much. Any user will 
tell you, felling bad about using AtomicBuzz(TM) E-Juice is chemically 
impossible.  Cosgrove had even considered asking AtomicBuzz(TM) for resources to 
research this little gem under the pretense that it was a cessation aid.  Best 
to not speak with them until absolutely necessary.

The package she received was hastily put together. No return address included, 
just a note that said ``no money back! good luck.'' She figured the seller was a
disgruntled researcher. Maybe this thing was a somebody's pet project. A grant 
dries up. Suddenly he's calculating neutron fluxes Denny Osborn's umpteenth cold 
fusion reactor. It ends up being warm fusion, two interns gets their atoms 
split, and the disgruntled researcher's calculations get blamed. Dr. Osborn 
receives a promotion for ``coming so close.''

Was that a flash? Cosgrove just made that up. She's nearly positive she just 
made that up out of thin air. She pulls the disk from behind her ear and puts it 
in her jacket pocket. Is this how it's supposed to work? She grabs her backup 
e-cig and jams it into her left nostril.  One long pull of SensationSystems(TM) 
Brain Wakin' Snortin' Salts 0.01% Anhydrous Ammonia E-Juice plants Cosgrove 
firmly in the here and now. Heart racing. Fight or flight or fight or flight or 
fight or

Cosgrove jumps up, slides across her desk, and nearly pulls the door off its 
hinges. She screams to no one in particular that the rest of her meetings should 
be cancelled. There is absolutely no time to waste. She runs down stairs, out 
the front gate, and hops into her Chrysler Sebring Convertible. Tires screech as 
she floors it out of the parking lot. She doesn't keep the seat real upright.  
She likes it laid back low. Her transitions lenses aren't even dark yet when she 
slams on the brakes. A young man with a slight build and thinning hair is 
strutting down the sidewalk with a mop. He walks over to the passenger side 
door.

``I'm a former janitor who's ready to start making his own messes.''

``Get in the car.''
